services:
  mysql:
    image: mysql:8
    container_name: mysql-vollmed
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: vollmed_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123